window.CONFIG = {
  SUPABASE_URL: 'YOUR_SUPABASE_URL',
  SUPABASE_ANON: 'YOUR_SUPABASE_ANON_KEY',
  EMAILJS_PUBLIC_KEY: 'YOUR_EMAILJS_PUBLIC_KEY',
  EMAILJS_SERVICE_ID: 'YOUR_EMAILJS_SERVICE_ID',
  EMAILJS_TEMPLATE_ADMIN: 'YOUR_EMAILJS_TEMPLATE_ADMIN',
  EMAILJS_TEMPLATE_USER: 'YOUR_EMAILJS_TEMPLATE_USER'
};
